services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: .
      dockerfile: ./packages/database/Dockerfile
    depends_on:
      - database
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
    command: ["sh", "-c", "npx prisma migrate dev && npx prisma generate"]

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    depends_on:
      - database
      - prisma-migrate
    ports:
      - "8080:8080"
    restart: always
    environment:
      - PORT=${PORT}
      - APP_URL=${APP_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network
    command: ["sh", "-c", "npm run build && node dist/index.js"]


  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    depends_on:
      - database
      - prisma-migrate
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    networks:
      - app-network


volumes:
      pgdata:

networks:
  app-network:
    driver: bridge

